site_name: mygeodev
repo_url: https://ezdanapak/mygeodev
theme:
  name: material
nav:
  - Home: index.md
  - Changelog: Changelog.md
  - Contributing: Contributing.md
  - FAQ: FAQ.md
  - Installation: Installation.md
  - Usage: Usage.md
  - Examples:
    - Intro: Examples/intro.md
    - Folium: Examples/Folium.md
    - Map: Examples/Map.md
    - Split map: Examples/Split_map.md
  - API Reference: API.md

      
